"use client";
import { useCallback, useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_FIA_API||"http://127.0.0.1:8001";
type O=Record<string,any>;
const f=(v:any,d=1)=>v===null||v===undefined||v===""?"—":Number.isFinite(Number(v))?Number(v).toFixed(d):String(v);
const p=(v:any,d=1)=>v===null||v===undefined?"—":`${f(v,d)}%`;
const tone=(v:any)=>Number(v)>0?"bull":Number(v)<0?"bear":"neutral";
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><div className="cardTitle">{title}</div>{children}</section>}
function Metric({label,value,sub}:{label:string;value:React.ReactNode;sub?:React.ReactNode}){return <div className="metric"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div>{sub?<div className="metricSub">{sub}</div>:null}</div>}
export default function Home(){
 const [d,setD]=useState<O|null>(null); const [err,setErr]=useState("");
 const load=useCallback(async()=>{try{setErr("");const r=await fetch(`${API}/api/dashboard`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);setD(await r.json())}catch(e:any){setErr(e?.message||"Dashboard API unavailable")}},[]);
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[load]);
 const live=d?.live||{}, snap=live.snapshot||{}, data=snap.data||{}, fc=live.forecast||{}, bt=d?.backtest||{}, sig=fc.signals||[], mega=data.mega_cap_details||{}, liq=live.liquidity||{}, up=live.upcoming_earnings?.events||[];
 return <main className="shell">
  <header className="topbar"><div><div className="eyebrow">AUTONOMOUS MARKET INTELLIGENCE</div><h1>CLEAR NASDAQ — FIA</h1><div className="subtitle">NASDAQ-100 / NQ · Next 4–8 Hours</div></div><div className="topActions"><div className={`statusDot ${snap.status==="LIVE"?"live":""}`}>{snap.status||"CONNECTING"}</div><button onClick={load}>Refresh</button></div></header>
  {err?<div className="errorBox">Backend connection: {err}</div>:null}
  <section className={`hero ${String(fc.direction||"").toLowerCase()}`}><div><div className="eyebrow">CURRENT FIA FORECAST</div><div className="heroDirection">{fc.direction||"—"}</div><div className="heroThesis">{fc.thesis||"Waiting for live FIA thesis."}</div></div><div className="probPanel"><div className="bigProb">{p(fc.bullish_probability)}</div><div className="probLabel">Bullish Probability</div><div className="probSplit"><span>Bull {p(fc.bullish_probability)}</span><span>Bear {p(fc.bearish_probability)}</span></div></div></section>
  <section className="metricGrid"><Metric label="Confidence" value={p(fc.confidence)}/><Metric label="Regime" value={fc.regime||"—"} sub={`Score ${f(fc.score,3)}`}/><Metric label="Data Coverage" value={p(Number(fc.data_coverage||0)*100)}/><Metric label="Intelligence Coverage" value={p(Number(fc.intelligence_coverage||0)*100)}/><Metric label="QQQ Price" value={f(data.price,2)} sub={`${f(data.change_percent,2)}% today`}/><Metric label="SPY" value={f(data.spx_price,2)} sub={`${f(data.spx_change_percent,2)}%`}/></section>
  <div className="twoCol"><Card title="Top Bullish Evidence"><div className="list">{(fc.bullish_evidence||[]).slice(0,6).map((x:any,i:number)=><div className="item bullLine" key={i}>{String(x)}</div>)}</div></Card><Card title="Top Bearish / Conflicting Evidence"><div className="list">{(fc.bearish_evidence||[]).slice(0,6).map((x:any,i:number)=><div className="item bearLine" key={i}>{String(x)}</div>)}</div></Card></div>
  <Card title="FIA Signal Breakdown"><div className="signalGrid">{sig.map((s:O,i:number)=><div className="signalRow" key={i}><div className="signalTop"><span>{s.name}</span><b className={tone(s.score)}>{Number(s.score)>=0?"+":""}{f(s.score,3)}</b></div><div className="barTrack"><div className={`barFill ${tone(s.score)}`} style={{width:`${Math.min(100,Math.abs(Number(s.score||0))*100)}%`}}/></div><div className="signalDetail">{s.detail}</div></div>)}</div></Card>
  <div className="twoCol"><Card title="Mega-cap Leadership"><div className="tickerGrid">{Object.entries(mega).map(([k,v]:[string,any])=><div className="ticker" key={k}><strong>{k}</strong><b className={tone(v.signal)}>{f(v.change_percent,2)}%</b></div>)}</div><div className="footerStats"><span>Mega <b>{f(data.mega_cap,3)}</b></span><span>Semis <b>{f(data.semis,3)}</b></span><span>Breadth <b>{f(data.breadth,3)}</b></span></div></Card><Card title="Macro / Rates / DXY"><div className="kvGrid"><Metric label="Fed Funds" value={f(data.fed_funds_rate,2)}/><Metric label="US 10Y" value={f(data.us10y_value,3)}/><Metric label="US10Y Signal" value={f(data.us10y,3)}/><Metric label="DXY / Rate Proxy" value={f(data.dxy,3)}/></div><div className="note">{data.macro_status||"—"}</div></Card></div>
  <Card title="NQ / QQQ Liquidity Map + Sweeps/Reclaims"><div className="liquidityGrid">{Object.entries(liq).map(([k,v]:[string,any])=><div className="liq" key={k}><div className="liqName">{v.name||k.replaceAll("_"," ")}</div><div className="liqPrice">{f(v.price,2)}</div><div className="liqMeta"><span>{v.timeframe||"—"}</span><span>{v.side||"—"}</span><span>{v.status||"—"}</span><span>{v.distance_pct!=null?`${f(v.distance_pct,3)}% away`:"—"}</span></div></div>)}</div><div className="footerStats"><span>Candle <b>{data.provider_candle_evidence||"—"}</b></span><span>Liquidity evidence <b>{String(data.liquidity_evidence_available??"—")}</b></span><span>Signal <b>{f(data.liquidity_signal,3)}</b></span></div></Card>
  <div className="twoCol"><Card title="News Intelligence"><div className="kvGrid"><Metric label="News Signal" value={f(data.news,3)}/><Metric label="Articles" value={data.news_articles??"—"}/><Metric label="Scored" value={data.news_scored_articles??"—"}/><Metric label="Source" value={fc.source_status?.news||"—"}/></div></Card><Card title="Upcoming Earnings / Catalysts"><div className="list">{up.length?up.slice(0,12).map((e:O,i:number)=><div className="event" key={i}><strong>{e.symbol}</strong><span>{e.date||"—"} · {e.hour||"time TBA"}</span><span>EPS est {f(e.eps_estimate,2)}</span></div>):<div className="empty">No tracked earnings in next 7 days, or provider unavailable.</div>}</div></Card></div>
  <div className="twoCol"><Card title="Risk + Invalidation"><div className="list">{(fc.invalidation||[]).map((x:string,i:number)=><div className="item risk" key={i}>{x}</div>)}</div></Card><Card title="Provider / Data Health"><div className="healthList">{Object.entries(fc.source_status||{}).map(([k,v])=><div className="healthRow" key={k}><span>{k}</span><b>{String(v)}</b></div>)}<div className="healthRow"><span>Quotes</span><b>{data.provider_quotes_available??"—"}/{data.provider_quotes_requested??"—"}</b></div><div className="healthRow"><span>Provider</span><b>{snap.provider||"—"}</b></div></div></Card></div>
  <section className="sectionHead"><div><div className="eyebrow">HISTORICAL VALIDATION</div><h2>FIA Historical Performance</h2></div><div className="phaseBadge">{bt.phase||"Backtest unavailable"}</div></section>
  <section className="metricGrid"><Metric label="1Y Forecasts" value={bt.forecasts??"—"}/><Metric label="4H Accuracy" value={p(bt.accuracy_4h?.accuracy,2)} sub={`n=${bt.accuracy_4h?.resolved??"—"}`}/><Metric label="8H Accuracy" value={p(bt.accuracy_8h?.accuracy,2)} sub={`n=${bt.accuracy_8h?.resolved??"—"}`}/><Metric label="4H Brier" value={f(bt.brier_4h?.brier,4)}/><Metric label="8H Brier" value={f(bt.brier_8h?.brier,4)}/><Metric label="Future EPS Used" value={bt.data_quality?.future_eps_used??"—"} sub="No-lookahead check"/></section>
  <div className="twoCol"><Card title="Confidence Accuracy"><div className="confidenceCompare"><div><b>4H</b>{(bt.confidence_4h||[]).map((x:O)=><div className="confidenceRow" key={x.band}><span>{x.band}</span><b>{p(x.accuracy,2)}</b><small>n={x.n}</small></div>)}</div><div><b>8H</b>{(bt.confidence_8h||[]).map((x:O)=><div className="confidenceRow" key={x.band}><span>{x.band}</span><b>{p(x.accuracy,2)}</b><small>n={x.n}</small></div>)}</div></div></Card><Card title="Earnings-Day vs Other-Day Performance">{["earnings_catalyst_days","other_days"].map(k=>{const x=bt.earnings_comparison?.[k]||{};return <div className="compareBlock" key={k}><strong>{k==="earnings_catalyst_days"?"Earnings catalyst days":"Other days"}</strong><span>{x.days??"—"} days</span><span>4H {p(x?.["4h"]?.accuracy,2)}</span><span>8H {p(x?.["8h"]?.accuracy,2)}</span></div>})}</Card></div>
  <Card title="Monthly Backtest Performance"><div className="tableWrap"><table><thead><tr><th>Month</th><th>Forecasts</th><th>4H</th><th>4H n</th><th>8H</th><th>8H n</th></tr></thead><tbody>{(bt.monthly||[]).map((m:O)=><tr key={m.month}><td>{m.month}</td><td>{m.forecasts}</td><td>{p(m.accuracy_4h,2)}</td><td>{m.resolved_4h}</td><td>{p(m.accuracy_8h,2)}</td><td>{m.resolved_8h}</td></tr>)}</tbody></table></div></Card>
  <Card title="Backtest Data Quality"><div className="healthList"><div className="healthRow"><span>Backtest file</span><b>{bt.file||"—"}</b></div><div className="healthRow"><span>Liquidity</span><b>{JSON.stringify(bt.data_quality?.liquidity_resolutions||{})}</b></div><div className="healthRow"><span>Contracts</span><b>{JSON.stringify(bt.data_quality?.liquidity_contracts||{})}</b></div><div className="healthRow"><span>News</span><b>{JSON.stringify(bt.data_quality?.news_evidence||{})}</b></div><div className="healthRow"><span>Earnings</span><b>{JSON.stringify(bt.data_quality?.earnings_evidence||{})}</b></div></div></Card>
  <footer>Educational research dashboard · Live forecast and historical backtest are separate · Auto-refresh 15s</footer>
 </main>
}
