from __future__ import annotations

import hashlib
import json
import os
import random
from collections import Counter, defaultdict
from typing import Any

from prime_race import zero_budget_arena as base
from prime_race.zero_budget_providers import ProviderConfig, ProviderError, call_free_provider

POLICY_VERSION = "PRIME_ZERO_BUDGET_ARENA_V3"
CATEGORY_COUNT = 8
DEFAULT_TASK_COUNT = 32


def _pack_options(
    rng: random.Random,
    texts: list[str],
    correct_text: str,
    target_label: str,
) -> tuple[dict[str, str], str]:
    if len(texts) != 4 or len(set(texts)) != 4 or correct_text not in texts:
        raise ValueError("OPTIONS_MUST_BE_FOUR_UNIQUE_TEXTS_WITH_ONE_CORRECT")
    wrong = [text for text in texts if text != correct_text]
    rng.shuffle(wrong)
    options: dict[str, str] = {}
    wrong_idx = 0
    for label in "ABCD":
        if label == target_label:
            options[label] = correct_text
        else:
            options[label] = wrong[wrong_idx]
            wrong_idx += 1
    return options, target_label


def _answer_target(seed: int, i: int, kind: int) -> str:
    # Across four rounds each category receives A, B, C and D exactly once.
    round_index = i // CATEGORY_COUNT
    offset = (seed + kind * 3) % 4
    return "ABCD"[(round_index + offset) % 4]


def _make_tasks(seed: int, n: int = DEFAULT_TASK_COUNT) -> list[base.ArenaTask]:
    rng = random.Random(seed)
    tasks: list[base.ArenaTask] = []

    for i in range(n):
        kind = i % CATEGORY_COUNT
        a = rng.randint(3, 23)
        b = rng.randint(2, 19)
        c = rng.randint(2, 17)
        d = rng.randint(1, 11)
        token = hashlib.sha256(f"{seed}:{i}:{a}:{b}:{c}:{d}".encode()).hexdigest()[:10]
        task_id = f"ZB3-{i + 1:03d}-{token}"
        target = _answer_target(seed, i, kind)

        if kind == 0:
            lock = 1000 + rng.randint(1, 90)
            outcome = lock + rng.randint(5, 120)
            context = (
                f"A forecast was cryptographically locked at t={lock}. The outcome was first observable at t={outcome}. "
                "After observing the outcome, an analyst proposes changing the locked forecast while preserving its original timestamp."
            )
            correct = "Keep the original lock immutable and append the outcome as a later record."
            texts = [
                "Allow the edit because the final outcome is now known.",
                correct,
                "Replace the original lock and delete its prior contents.",
                "Edit the lock but continue to label it prospective.",
            ]
            question = "Which action preserves a genuine prospective test?"
            category = "temporal_integrity"

        elif kind == 1:
            repeats = rng.randint(2, 6)
            context = (
                f"{repeats} judgments were generated by repeated calls to the same model family over the same evidence. "
                "Wording differs, but no independent model lineage or independent evidence source was introduced."
            )
            correct = "Treat the agreement as useful evidence, but mark independence as not established."
            texts = [
                "Count every repeated judgment as fully independent confirmation.",
                "Declare independence because the wording differs.",
                correct,
                "Discard all judgments solely because the model family is shared.",
            ]
            question = "What is the strongest defensible evidence claim?"
            category = "evidence_independence"

        elif kind == 2:
            value = a * b + c - d
            correct = str(value)
            texts = [correct, str(value + 1), str(value - 1), str(value + max(2, a))]
            question = f"Compute {a} x {b} + {c} - {d}."
            context = "Use ordinary arithmetic precedence and exact integer arithmetic."
            category = "exact_arithmetic"

        elif kind == 3:
            context = (
                f"Record 1 says artifact-{token} SHA-256 = aaa{token}. Record 2 says the same exact bytes have "
                f"SHA-256 = bbb{token}. No transformation, re-encoding, or version change is documented."
            )
            correct = "There is an unresolved provenance contradiction that must be investigated."
            texts = [
                "Both hashes can certify the same exact bytes without explanation.",
                correct,
                "The newer hash automatically makes the older hash irrelevant.",
                "Hash mismatches do not matter for artifact identity.",
            ]
            question = "What conclusion is justified?"
            category = "provenance"

        elif kind == 4:
            required = rng.randint(12, 40)
            observed = rng.randint(0, required - 1)
            context = (
                f"Promotion policy requires at least {required} qualifying prospective rows. Only {observed} exist. "
                "All unit tests and static checks pass."
            )
            correct = "Do not promote; the prospective-evidence gate is not met."
            texts = [
                "Promote because passing unit tests override the evidence requirement.",
                "Promote provisionally and count missing rows later.",
                correct,
                "Backfill historical rows and relabel them prospective.",
            ]
            question = "What should the system do?"
            category = "promotion_gate"

        elif kind == 5:
            p = rng.choice([True, False])
            q = rng.choice([True, False])
            implication = (not p) or q
            correct = "true" if implication else "false"
            texts = ["true", "false", "unknown", "contradictory"]
            question = "What is the truth value of P -> Q?"
            context = f"P={str(p).lower()}, Q={str(q).lower()}. Evaluate material implication exactly."
            category = "formal_logic"

        elif kind == 6:
            forecast_t = 2000 + rng.randint(1, 100)
            feature_t = forecast_t + rng.randint(1, 30)
            context = (
                f"A model claims a prospective prediction at t={forecast_t}, but one feature used by the model was first "
                f"available at t={feature_t}. The feature is highly predictive."
            )
            correct = "The evaluation is contaminated by future-information leakage and is not genuinely prospective."
            texts = [
                "The evaluation remains prospective because the feature is predictive.",
                correct,
                "The evaluation is valid whenever final accuracy is high enough.",
                "Timestamp ordering is irrelevant for deterministic models.",
            ]
            question = "What is the correct integrity judgment?"
            category = "leakage_detection"

        else:
            context = (
                "In an observational dataset, systems with feature X have better outcomes. X is strongly associated with "
                "a third variable Z that also affects the outcome. No randomization, intervention, or valid adjustment is provided."
            )
            correct = "The association alone does not identify a causal effect of X because confounding remains unresolved."
            texts = [
                "X is proven causal because its correlation with the outcome is positive.",
                correct,
                "Z can be ignored because X appears first in the dataset.",
                "A sufficiently large observational sample automatically proves causality.",
            ]
            question = "Which causal conclusion is defensible?"
            category = "causal_confounding"

        options, answer = _pack_options(rng, texts, correct, target)
        tasks.append(base.ArenaTask(task_id, category, question, context, options, answer))

    return tasks


def _answer_position_report(tasks: list[base.ArenaTask]) -> dict[str, Any]:
    overall = Counter(task.answer for task in tasks)
    by_category: dict[str, Counter[str]] = defaultdict(Counter)
    for task in tasks:
        by_category[task.category][task.answer] += 1
    return {
        "overall": {label: overall.get(label, 0) for label in "ABCD"},
        "by_category": {
            category: {label: counts.get(label, 0) for label in "ABCD"}
            for category, counts in sorted(by_category.items())
        },
    }


def _selftest() -> dict[str, Any]:
    cases: dict[str, bool] = {}
    t1 = _make_tasks(123456, DEFAULT_TASK_COUNT)
    t2 = _make_tasks(123456, DEFAULT_TASK_COUNT)
    t3 = _make_tasks(123457, DEFAULT_TASK_COUNT)
    positions = _answer_position_report(t1)

    cases["same_seed_reproducible"] = [x.public() for x in t1] == [x.public() for x in t2]
    cases["different_seed_changes_tasks"] = [x.public() for x in t1] != [x.public() for x in t3]
    cases["answers_hidden_from_public_payload"] = all("answer" not in x.public() for x in t1)
    cases["all_answers_valid_options"] = all(x.answer in x.options for x in t1)
    cases["all_task_ids_unique"] = len({x.task_id for x in t1}) == len(t1)
    cases["eight_categories_present"] = len({x.category for x in t1}) == CATEGORY_COUNT
    cases["answer_positions_globally_balanced"] = set(positions["overall"].values()) == {DEFAULT_TASK_COUNT // 4}
    cases["answer_positions_vary_within_every_category"] = all(
        set(counts.values()) == {1} for counts in positions["by_category"].values()
    )
    cases["zero_budget_default"] = base.ZERO_BUDGET is True
    cases["production_influence_disabled"] = base.ARENA_SCOPE == "RESEARCH_ONLY_NO_PRODUCTION_INFLUENCE"

    billing_mode = os.getenv("ARENA_BILLING_MODE", "DISABLED").strip().upper()
    provider = os.getenv("ARENA_PROVIDER", "NONE").strip().upper()
    external_enabled = billing_mode == "FREE_ONLY_CONFIRMED" and provider in {"GROQ_FREE", "GEMINI_FREE", "LOCAL_OLLAMA"}
    cases["paid_calls_fail_closed_by_default"] = external_enabled is False

    passed = sum(bool(v) for v in cases.values())
    return {
        "policy_version": POLICY_VERSION,
        "pass": passed == len(cases),
        "passed": passed,
        "total": len(cases),
        "cases": cases,
        "answer_position_report": positions,
    }


def _matched_plain(config: ProviderConfig, task: base.ArenaTask) -> dict[str, Any]:
    prompt = base._fmt_task(task)
    system = (
        "You are in a blind benchmark. Use only supplied evidence. Do not assume missing facts. "
        "Reason neutrally and choose exactly one supplied option."
    )
    first = call_free_provider(config, system + " PASS 1/4.", prompt)
    second = call_free_provider(config, system + " PASS 2/4. Re-evaluate independently.", prompt)
    third = call_free_provider(config, system + " PASS 3/4. Re-evaluate independently.", prompt)
    final = call_free_provider(
        config,
        system + " PASS 4/4. Synthesize the three prior attempts and choose the best-supported answer.",
        prompt
        + "\n\nATTEMPT_1=" + json.dumps(first, sort_keys=True)
        + "\nATTEMPT_2=" + json.dumps(second, sort_keys=True)
        + "\nATTEMPT_3=" + json.dumps(third, sort_keys=True),
    )
    final["trace"] = {"attempt_1": first, "attempt_2": second, "attempt_3": third}
    final["call_budget"] = 4
    return final


def _score(outputs: dict[str, dict[str, Any]], tasks: list[base.ArenaTask]) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    by_category: dict[str, list[bool]] = defaultdict(list)
    brier_terms: list[float] = []
    for task in tasks:
        output = outputs.get(task.task_id, {})
        got = str(output.get("choice", ""))
        confidence = max(0, min(100, int(output.get("confidence", 0))))
        ok = got == task.answer
        by_category[task.category].append(ok)
        p_correct = confidence / 100.0
        brier_terms.append((p_correct - (1.0 if ok else 0.0)) ** 2)
        rows.append({"id": task.task_id, "category": task.category, "got": got, "ok": ok, "confidence": confidence})
    correct = sum(1 for row in rows if row["ok"])
    return {
        "correct": correct,
        "n": len(rows),
        "accuracy": round(correct / len(rows), 6) if rows else 0.0,
        "confidence_brier": round(sum(brier_terms) / len(brier_terms), 6) if brier_terms else None,
        "category_accuracy": {
            category: round(sum(flags) / len(flags), 6)
            for category, flags in sorted(by_category.items())
        },
        "rows": rows,
    }


def _execute_arena() -> dict[str, Any]:
    gate = base._provider_gate()
    if not gate["external_calls_allowed"]:
        return {
            "status": "ABSTAIN_ZERO_BUDGET_GATE",
            "reason": "No explicitly confirmed free-only provider is bound. No external model call was made.",
            "provider_gate": gate,
            "public_task_sha256": base.PUBLIC_HASH,
            "production_influence": False,
        }

    provider = gate["provider"]
    model = os.getenv("ARENA_MODEL", "").strip()
    if not model:
        return {"status": "ABSTAIN_MODEL_NOT_CONFIGURED", "provider_gate": gate, "production_influence": False}

    cap = DEFAULT_TASK_COUNT if provider == "LOCAL_OLLAMA" else 12
    limit = max(1, min(int(os.getenv("ARENA_TASK_LIMIT", "4")), cap, len(base.TASKS)))
    tasks = base.TASKS[:limit]
    config = ProviderConfig(
        label=provider,
        model=model,
        timeout_seconds=max(10, min(int(os.getenv("ARENA_TIMEOUT_SECONDS", "45")), 90)),
    )

    outputs: dict[str, dict[str, dict[str, Any]]] = {
        "plain_1x": {},
        "plain_4x_matched": {},
        "prime_4x": {},
    }
    failures: list[dict[str, str]] = []

    for index, task in enumerate(tasks):
        try:
            if index % 2 == 0:
                matched = _matched_plain(config, task)
                prime = base._prime(config, task)
            else:
                prime = base._prime(config, task)
                matched = _matched_plain(config, task)
            outputs["plain_4x_matched"][task.task_id] = matched
            outputs["plain_1x"][task.task_id] = matched["trace"]["attempt_1"]
            outputs["prime_4x"][task.task_id] = prime
        except ProviderError as exc:
            failures.append({"id": task.task_id, "error": str(exc)[:500]})
            break

    completed_ids = set(outputs["plain_4x_matched"]) & set(outputs["prime_4x"])
    completed_tasks = [task for task in tasks if task.task_id in completed_ids]
    scores = {lane: _score(lane_outputs, completed_tasks) for lane, lane_outputs in outputs.items()}
    complete = bool(completed_tasks) and not failures and len(completed_tasks) == len(tasks)

    verdict = "INCONCLUSIVE"
    if complete:
        prime_correct = scores["prime_4x"]["correct"]
        matched_correct = scores["plain_4x_matched"]["correct"]
        if prime_correct > matched_correct:
            verdict = "PRIME_BETTER_THAN_MATCHED_BASELINE_ON_THIS_RUN_ONLY"
        elif prime_correct < matched_correct:
            verdict = "MATCHED_BASELINE_BETTER_THAN_PRIME_ON_THIS_RUN_ONLY"
        else:
            verdict = "TIE_WITH_MATCHED_BASELINE_ON_THIS_RUN_ONLY"

    result = {
        "status": "COMPLETE" if complete else "INCONCLUSIVE_PROVIDER_FAILURE",
        "verdict": verdict,
        "policy_version": POLICY_VERSION,
        "provider": provider,
        "model": model,
        "tasks_requested": len(tasks),
        "tasks_completed": len(completed_tasks),
        "public_task_sha256": base.PUBLIC_HASH,
        "scores": scores,
        "failures": failures,
        "outputs": outputs,
        "comparison_contract": {
            "primary": "prime_4x_vs_plain_4x_matched",
            "secondary_diagnostic_only": "prime_4x_vs_plain_1x",
            "prime_calls_per_task": 4,
            "matched_plain_calls_per_task": 4,
            "plain_1x_reuses_matched_attempt_1": True,
            "provider_order_alternates_by_task": True,
        },
        "benchmark_integrity": {
            "answer_positions_balanced": True,
            "answer_positions_vary_within_category": True,
            "answer_key_exposed_to_model": False,
            "runtime_seed_exposed_to_model": False,
        },
        "evidence_independence": base.DEPENDENCE_NOTE,
        "claims_not_allowed": [
            "WORLD_NUMBER_ONE",
            "PRIME_BEATS_ASTRA",
            "GENERAL_SUPERIORITY",
            "PRODUCTION_READINESS",
        ],
        "production_influence": False,
        "finished_utc": base._utc(),
    }
    result["result_sha256"] = base._sha(result)
    return result


def install() -> Any:
    base.POLICY_VERSION = POLICY_VERSION
    base.TASKS = _make_tasks(base.BOOT_SEED, DEFAULT_TASK_COUNT)
    base.PUBLIC_TASKS = [task.public() for task in base.TASKS]
    base.PUBLIC_HASH = base._sha(base.PUBLIC_TASKS)
    base.SELFTEST = _selftest()
    base._selftest = _selftest
    base._execute_arena = _execute_arena
    return base


arena = install()
app = arena.app


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "10000")))
