"use client";
import { useEffect, useState } from "react";
type AnyObj = Record<string, any>;
function Metric({label,value,sub}:{label:string,value:any,sub?:string}){return <div style={{padding:"14px 16px",border:"1px solid rgba(148,163,184,.18)",borderRadius:14,background:"rgba(15,23,42,.54)"}}><div style={{fontSize:11,letterSpacing:".08em",opacity:.62,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:27,fontWeight:750,lineHeight:1.2,marginTop:4}}>{value ?? "—"}</div>{sub?<div style={{fontSize:11,opacity:.58,marginTop:4}}>{sub}</div>:null}</div>}
export default function WholeSystemBacktestPanel(){
 const [d,setD]=useState<AnyObj|null>(null);useEffect(()=>{let alive=true;const load=()=>fetch("/api/fia/whole-system-backtest",{cache:"no-store"}).then(r=>r.json()).then(x=>{if(alive)setD(x)}).catch(()=>{});load();const id=setInterval(load,30000);return()=>{alive=false;clearInterval(id)}},[]);
 const h4=d?.horizons?.["4h"]||{};const h8=d?.horizons?.["8h"]||{};const p=d?.progress;const isFinal=Boolean(d?.final);
 return <section style={{margin:"0 0 20px",padding:18,border:"1px solid rgba(148,163,184,.22)",borderRadius:18,background:"linear-gradient(180deg,rgba(2,6,23,.78),rgba(15,23,42,.56))"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:14}}><div><div style={{fontSize:11,opacity:.58,letterSpacing:".12em"}}>RETROSPECTIVE 1Y · ACTUAL V6.6 · 4H + 8H</div><div style={{fontSize:20,fontWeight:750}}>Whole-System Genuine Win/Loss Proof</div></div><div>{isFinal?"FINAL":"RUNNING"} {p?`· ${p.pct ?? 0}%`:""}</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10}}><Metric label="4H win rate" value={h4.win_rate==null?"—":`${h4.win_rate}%`} sub={`W ${h4.wins??0} · L ${h4.losses??0}`}/><Metric label="8H win rate" value={h8.win_rate==null?"—":`${h8.win_rate}%`} sub={`W ${h8.wins??0} · L ${h8.losses??0}`}/><Metric label="4H coverage" value={h4.directional_coverage_pct==null?"—":`${h4.directional_coverage_pct}%`}/><Metric label="8H coverage" value={h8.directional_coverage_pct==null?"—":`${h8.directional_coverage_pct}%`}/><Metric label="4H Brier" value={h4.brier??"—"}/><Metric label="8H Brier" value={h8.brier??"—"}/></div><div style={{fontSize:11,opacity:.55,marginTop:12}}>One locked V6.6 forecast is resolved against genuine 4H and 8H outcomes. 4H is not falsely presented as a separate second Brain run. <a href="/whole-system-backtest" style={{textDecoration:"underline"}}>Full report</a></div></section>
}
