"use client";
import React,{useEffect,useRef,useState} from "react";
export default function Page(){
 const [d,setD]=useState<any>(null); const [prompt,setPrompt]=useState(""); const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let ws=new WebSocket(`ws://${location.hostname}:8001/api/phase34/stream`); ws.onmessage=e=>{try{setD(JSON.parse(e.data))}catch{}}; return()=>ws.close()},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const gl=c.getContext("webgl");if(!gl)return;gl.viewport(0,0,c.width,c.height);gl.clearColor(.025,.04,.07,1);gl.clear(gl.COLOR_BUFFER_BIT)},[d]);
 const voice=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR)return alert("SpeechRecognition not supported in this browser");const r=new SR();r.onresult=(e:any)=>setPrompt(e.results[0][0].transcript);r.start()}
 return <main style={{background:"#071018",color:"#e9f3ff",minHeight:"100vh",padding:24,fontFamily:"system-ui"}}><h1>FIA Phase 34 · ALL-POINTS PRE-MOVE</h1><p>23/23 architecture · research-only · no broker execution.</p><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12}}>{[["State",d?.state],["Direction",d?.direction],["Strength",d?.strength],["Coverage",d?.coverage],["Alert",d?.alert?.fire?"FIRE":"HOLD"]].map(([a,b])=><div key={a as string} style={{border:"1px solid #28445a",borderRadius:14,padding:18}}><small>{a}</small><div style={{fontSize:26,fontWeight:700}}>{String(b??"—")}</div></div>)}</section><h2>WebGL Volatility / Regime Surface</h2><canvas ref={canvas} width={960} height={360} style={{width:"100%",border:"1px solid #28445a",borderRadius:14}}/><h2>AI Copilot</h2><div style={{display:"flex",gap:8}}><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask about pre-move evidence" style={{flex:1,padding:12}}/><button onClick={voice}>🎙 Voice</button></div><p><a href="/phase34/replay" style={{color:"#8bd3ff"}}>Open tick/replay lab →</a></p></main>
}
