"""Phase 04 — FIA accuracy and probability metrics.

Reads saved prediction/outcome records and produces deterministic summaries.
No model fitting is performed here; this phase measures the existing FIA.
"""
from __future__ import annotations

import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


def _f(v):
    try:
        return None if v is None or v == "" else float(v)
    except (TypeError, ValueError):
        return None


def load_jsonl(path: str | Path) -> List[Dict[str, Any]]:
    path = Path(path)
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def _predicted_direction(row: Dict[str, Any]) -> Optional[str]:
    bull, bear = _f(row.get("bullish_probability")), _f(row.get("bearish_probability"))
    if bull is None and bear is None:
        return None
    if bull is None:
        return "bearish"
    if bear is None:
        return "bullish"
    if bull > bear:
        return "bullish"
    if bear > bull:
        return "bearish"
    return "flat"


def _confidence(row: Dict[str, Any]) -> Optional[float]:
    vals = [_f(row.get("bullish_probability")), _f(row.get("bearish_probability"))]
    vals = [v for v in vals if v is not None]
    return max(vals) if vals else None


def _bucket(conf: float) -> str:
    # Probabilities may be stored as 0..1 or 0..100.
    p = conf * 100.0 if 0 <= conf <= 1 else conf
    starts = [50, 55, 60, 65, 70, 75, 80, 85]
    for start in starts:
        if p < start + 5:
            return f"{start}-{start+5}%"
    return "85%+"


def evaluate(predictions: Iterable[Dict[str, Any]], outcomes: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    preds = list(predictions)
    outs = list(outcomes)
    pred_by_id = {str(p.get("id") or p.get("prediction_id")): p for p in preds}

    # Prediction IDs are generated by Phase 03; outcomes already carry them.
    joined = []
    for o in outs:
        p = pred_by_id.get(str(o.get("prediction_id")))
        if p:
            joined.append((p, o))

    by_horizon = defaultdict(list)
    for p, o in joined:
        by_horizon[str(o.get("horizon", "unknown"))].append((p, o))

    def summarize(items):
        evaluated = 0
        correct = 0
        returns = []
        maes = []
        mfes = []
        brier_terms = []
        for p, o in items:
            actual = str(o.get("direction") or "").lower()
            pred = _predicted_direction(p)
            if actual not in {"bullish", "bearish"} or pred not in {"bullish", "bearish"}:
                continue
            evaluated += 1
            correct += int(pred == actual)
            r = _f(o.get("return_pct"))
            if r is not None:
                returns.append(r)
            mae = _f(o.get("mae_pct")); mfe = _f(o.get("mfe_pct"))
            if mae is not None: maes.append(mae)
            if mfe is not None: mfes.append(mfe)
            bull = _f(p.get("bullish_probability"))
            if bull is not None:
                if bull > 1: bull /= 100.0
                actual_bull = 1.0 if actual == "bullish" else 0.0
                brier_terms.append((bull - actual_bull) ** 2)
        return {
            "total_joined": len(items),
            "evaluated": evaluated,
            "correct": correct,
            "wrong": evaluated - correct,
            "accuracy_pct": (correct / evaluated * 100.0) if evaluated else None,
            "avg_return_pct": (sum(returns) / len(returns)) if returns else None,
            "avg_mfe_pct": (sum(mfes) / len(mfes)) if mfes else None,
            "avg_mae_pct": (sum(maes) / len(maes)) if maes else None,
            "brier_score": (sum(brier_terms) / len(brier_terms)) if brier_terms else None,
        }

    buckets = defaultdict(list)
    for p, o in joined:
        actual = str(o.get("direction") or "").lower()
        pred = _predicted_direction(p)
        conf = _confidence(p)
        if actual in {"bullish", "bearish"} and pred in {"bullish", "bearish"} and conf is not None:
            buckets[_bucket(conf)].append((p, o))

    bucket_summary = {}
    order = ["50-55%", "55-60%", "60-65%", "65-70%", "70-75%", "75-80%", "80-85%", "85%+"]
    for b in order:
        s = summarize(buckets.get(b, []))
        bucket_summary[b] = s

    return {
        "joined_predictions": len(joined),
        "horizons": {h: summarize(items) for h, items in sorted(by_horizon.items())},
        "confidence_buckets": bucket_summary,
    }


def write_report(result: Dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    return path
